@startuml

package Question_1 {

interface account{
    
    void deposit()
    void withdraw()
}
class current {
    - double balance
    void getbalance()
    deposit()
    withdraw()
}

class demat{
    - balance 
    void getbalance()
    void liquidate()
    void invest()

}

class fd{
    int time 
    - double amount
    void setamount()
    int intrest()
    long getamount()
}

class savings{
    - double balance
    void getbalance()
    deposit()
    withdraw()
}
}

current *-- account
savings *-- account


@enduml